### ISSUE TITLE
[BUG]: Fix Navbar Section 

### ISSUE THREAD

**Issue by Geeks-Arpan** [Shinjan-saha/Canteen-Website#1]
Fix navbar to see the logo properly

Assign me under Apertre'24

**Comment by Shinjan-saha** [comment]
@Geeks-Arpan you have been assigned this issue in case of any doubt feel free to ask me 

Happy Coding

**Comment by Shinjan-saha** [comment]
Update of task?

**Comment by Sapta-Dev27** [comment]
I want to do this task , please assign me this issue

**Comment by Shinjan-saha** [comment]
Done
