### ISSUE TITLE
Change the CSS of the images and texts of Stationary,Icecream,Printing,Beverages & Main Section 

### ISSUE THREAD

**Issue by Sapta-Dev27** [Shinjan-saha/Canteen-Website#11]
I  would like to contribute in this project . Change the CSS of the images and texts by adding hover effects . The price and the name of the commodities will be hidden initially , while you hover on the image the price and name will be shown on the image by a sliding effect carousel.

**Comment by Shinjan-saha** [comment]
@Sapta-Dev27 you have been assigned this in case of any doubt feel free to ask me 

Happy Coding
