### ISSUE TITLE
[UI]Adding Smooth scrolling

### ISSUE THREAD

**Issue by Tuhin114** [Shinjan-saha/Canteen-Website#16]
I want to add smooth scrolling through the navbar to all pages....please assign me..

**Comment by Shinjan-saha** [comment]
Can you explain your work in brief on how you want to do it?

**Comment by Tuhin114** [comment]
@Shinjan-saha Yeah..I am attaching another project where I have done the same smooth scrolling....

https://github.com/Shinjan-saha/Canteen-Website/assets/132370086/2b105152-3d6d-4639-81af-5bd227c70c50

**Comment by Shinjan-saha** [comment]
@Tuhin114 nice one i have assigned you this issue

**Comment by Tuhin114** [comment]
@Shinjan-saha ok...thank you....I will soon make the PR

**Comment by Shinjan-saha** [comment]
Update on Task?

**Comment by Tuhin114** [comment]
Sorry I am facing some issues...and i am a little bit busy with my CA exam...you can unassign me...

**Comment by Sneha123-zudo** [comment]
Please assign me this issue , I'm intrested in solving these issue.

**Comment by Shinjan-saha** [comment]
Assigned you the issue

**Comment by Shinjan-saha** [comment]
Update of the Task?

**Comment by Sneha123-zudo** [comment]
Working on it

**Comment by Shinjan-saha** [comment]
PR MERGED
