### ISSUE TITLE
Add light and dark mode button in website 

### ISSUE THREAD

**Issue by Sneha123-zudo** [Shinjan-saha/Canteen-Website#22]

**Comment by Sneha123-zudo** [comment]
I can add a light and mode button in canteen website as a feature . Please assign me this issue

**Comment by Shinjan-saha** [comment]
Are you going to add just the button or going to create a full fledge dark mode of the website?

**Comment by Sneha123-zudo** [comment]
A button , like when we click on that button they will change their mode from light to dark and same from dark to light mode.

**Comment by Shinjan-saha** [comment]
But there is no dark Mode Made in the website You have to create it & then the button will just switch between those mode

**Comment by Sneha123-zudo** [comment]
<img width="941" alt="Button light to dark mode" src="https://github.com/Shinjan-saha/Canteen-Website/assets/145490348/38513160-e856-4d55-af13-bab228cf0664">

Something like this, I have made it but some modification is still required

**Comment by Shinjan-saha** [comment]
Ok i am assigning you this but dark Ui must be good

**Comment by Shinjan-saha** [comment]
Update of your Task?

**Comment by Sneha123-zudo** [comment]
I am working on it , i will make PR tommorow

**Comment by Shinjan-saha** [comment]
Great Work  
Awesome Merged Your PR
