### ISSUE TITLE
the div containing the text needs better css (rounding off the corners, etc.)

### ISSUE THREAD

**Issue by deepbeatz** [Shinjan-saha/Canteen-Website#28]
<img width="313" alt="Screenshot 2024-01-08 130537" src="https://github.com/Shinjan-saha/Canteen-Website/assets/79015311/eaf2da48-5ec7-405b-a09d-856122a6d130">

**Comment by deepbeatz** [comment]
@Shinjan-saha assign me this issue under apertre

**Comment by Shinjan-saha** [comment]
@deepbeatz assigned you the issue

**Comment by Shinjan-saha** [comment]
Update of the Task?

**Comment by deepbeatz** [comment]
#38 pr sent @Shinjan-saha

**Comment by Shinjan-saha** [comment]
Done PR Merged
