### ISSUE TITLE
Add an online delivery option to hostel areas and also surrounding locals.

### ISSUE THREAD

**Issue by nsrs-78** [Shinjan-saha/Canteen-Website#3]

**Comment by nsrs-78** [comment]
Can I contribute to this ?

**Comment by Shinjan-saha** [comment]
Nice idea can you elaborate on it please on how will you approach to this issue 
We can further discuss this on discord

**Comment by nsrs-78** [comment]
Okay Let me show u a demo . 
![Screenshot 2024-01-02 161440](https://github.com/Shinjan-saha/Canteen-Website/assets/137761848/edd39ae1-91db-40e7-828a-74786bde0698)
![Screenshot 2024-01-02 161453](https://github.com/Shinjan-saha/Canteen-Website/assets/137761848/92d32d81-c329-4577-8355-ae5158019805)

I'll build these pages . And every "READ MORE " opt will finally head to the main post page.

**Comment by nsrs-78** [comment]
![Screenshot 2024-01-02 171600](https://github.com/Shinjan-saha/Canteen-Website/assets/137761848/84dfb77f-29ad-4d8c-8b19-0578965ebd4f)
After clicking the order now opt will lead to another page to add diff items to cart and then final checkout.

**Comment by nsrs-78** [comment]
1st : 
![Screenshot 2024-01-02 171600](https://github.com/Shinjan-saha/Canteen-Website/assets/137761848/97053c44-44de-4b50-986e-b394b0f653b8)
2nd:
![Screenshot 2024-01-02 172035](https://github.com/Shinjan-saha/Canteen-Website/assets/137761848/34657cb1-1633-4d23-b879-9aae2086c2cd)
3rd:
![Screenshot 2024-01-02 172108](https://github.com/Shinjan-saha/Canteen-Website/assets/137761848/a1526964-ce9b-45c4-b56f-75d88606fd5b)
4th:
![Screenshot 2024-01-02 172124](https://github.com/Shinjan-saha/Canteen-Website/assets/137761848/359d1422-8bd5-4e65-b239-943ed3789d2c)


This is just a demo idea. The final UI will be different.

**Comment by Shinjan-saha** [comment]
So it's an Cart System like an ecommerce website right?

**Comment by nsrs-78** [comment]
yopp

**Comment by Shinjan-saha** [comment]
Very good then I will assign it to you tomorrow when apertre 24 Officially starts

**Comment by nsrs-78** [comment]
Tnxx

**Comment by Shinjan-saha** [comment]
@nsrs-78 I have assigned it to you, any case if you have any doubt ask me i will be there to help

Happy Coding

**Comment by nsrs-78** [comment]
Tnxx

**Comment by Shinjan-saha** [comment]
Work Done upto Satisfactory 
Good Work @nsrs-78
