### ISSUE TITLE
ADD Header and footer in cart.html

### ISSUE THREAD

**Issue by rko0211** [Shinjan-saha/Canteen-Website#33]
![Screenshot from 2024-01-10 12-09-03](https://github.com/Shinjan-saha/Canteen-Website/assets/97402824/98cbbdd9-0d62-4df3-a955-9da4a1d83790)
![Screenshot from 2024-01-10 12-09-08](https://github.com/Shinjan-saha/Canteen-Website/assets/97402824/a5cdb17e-fd45-4c6d-9def-b1bcb3af5e7c)

Kindly review my issue and assign me under apertre24.

**Comment by Shinjan-saha** [comment]
Update on Task?

**Comment by rko0211** [comment]
Yes I will send PR for this by tonight
