### ISSUE TITLE
UI Update: Make the footer section more attractive

### ISSUE THREAD

**Issue by IndraniSom** [Shinjan-saha/Canteen-Website#4]
Hello, I am participating in Apetre-24 I want to work on the footer section to make it more attractive. Can you assign me in this issue?

**Comment by Shinjan-saha** [comment]
Can you elaborate on it please on how will you approach to this issue
We can further discuss this on discord

**Comment by IndraniSom** [comment]
I have elaborated the issue in the discord channel 
Kindly check it and if you find it relevant please assign me in this issue :)

**Comment by Shinjan-saha** [comment]
@IndraniSom i have assigned you the issue 

Happy Coding

**Comment by IndraniSom** [comment]
![picu](https://github.com/Shinjan-saha/Canteen-Website/assets/121074944/62988ce1-f2e0-40f8-9e8a-58b333e9e1da)
this is the footer section i have made can i send the PR now?

**Comment by Shinjan-saha** [comment]
All work done upto Satisfactory
