### ISSUE TITLE
Contact form should be in different page

### ISSUE THREAD

**Issue by rko0211** [Shinjan-saha/Canteen-Website#48]
We should kept the contact form in different page and add extra option in navbar. Kindly review my PR. Thank you.

![Screenshot from 2024-01-12 22-33-07](https://github.com/Shinjan-saha/Canteen-Website/assets/97402824/a3f73603-29b1-4cd2-9c9f-52d96cfa3fd3)

**Comment by Shinjan-saha** [comment]
So i don't think it will be a Good Idea , Contact should be there with Loctation only
