### ISSUE TITLE
Feature add in README.md

### ISSUE THREAD

**Issue by apu52** [Shinjan-saha/Canteen-Website#50]
**Describe the feature you are requesting**

Hello Sir,
I want to add some cool badges in this repo like
- open issues
- contributor
- open PR
- last commites
this type of cool API badges
It will be very helpful to showcase the stats of your Repo as well as will attract more contributors.
**Additional context(if any)**

![image](https://github.com/Shinjan-saha/Canteen-Website/assets/114172928/0dd3cb72-b698-4a45-aa89-a9a13c2ebefe)

***Are you contributing under any open-source program ?***

APERTRE'24

**Comment by apu52** [comment]
@Shinjan-saha Please assign me this issue under APERTRE'24

**Comment by Shinjan-saha** [comment]
Assigned you the issue
