### ISSUE TITLE
Order online button need to be alligned correctly in mobile device

### ISSUE THREAD

**Issue by rko0211** [Shinjan-saha/Canteen-Website#54]
![Screen Shot 2024-01-13 at 15 09 53](https://github.com/Shinjan-saha/Canteen-Website/assets/97402824/7bd7291e-3f59-47f8-a77a-dc3a34c170d7)

**Comment by Shinjan-saha** [comment]
You are assigned

**Comment by Shinjan-saha** [comment]
Done
