### ISSUE TITLE
Add Scroll back button in the website 

### ISSUE THREAD

**Issue by rko0211** [Shinjan-saha/Canteen-Website#61]

**Comment by Shinjan-saha** [comment]
Please explain your Issue in brief

**Comment by rko0211** [comment]
When user visit your website and reach to the footer part then to come back in the header part we can make a beautiful button to do it without scrolling back manually..

**Comment by Shinjan-saha** [comment]
Assigned you the issue

**Comment by Shinjan-saha** [comment]
PR merged
