### ISSUE TITLE
Editing the README

### ISSUE THREAD

**Issue by abhraneel2004** [Shinjan-saha/Canteen-Website#63]
The readme needs some updation.
I will add how can someone contribute to this repo and the basic installation of the technology used.

**Comment by Shinjan-saha** [comment]
Can you please give a more brief on about who will you edit it?

**Comment by abhraneel2004** [comment]
I will add the steps of:
how to fork this repo. 
how to contribute.
how to install and run the mentioned technology (HTML, CSS, JS, Flutter)
also add the repository stats

**Comment by Shinjan-saha** [comment]
Assigned you the issue

**Comment by Shinjan-saha** [comment]
PR Merged
