### ISSUE TITLE
In the Mobile Version the About is not visible Properly  in Cart Page

### ISSUE THREAD

**Issue by Shinjan-saha** [Shinjan-saha/Canteen-Website#68]
<img width="176" alt="Aboutprob" src="https://github.com/Shinjan-saha/Canteen-Website/assets/116014977/ef6d479c-608f-4870-b7b8-34bc45ee94bb">

Fix the spacing between the  About & the Navbar in the Mobile Version

**Comment by rko0211** [comment]
Kindly assign me this task

**Comment by Shinjan-saha** [comment]
PR Merged
