### ISSUE TITLE
Add image hover effect 

### ISSUE THREAD

**Issue by rko0211** [Shinjan-saha/Canteen-Website#70]
![Screenshot from 2024-01-16 22-53-15](https://github.com/Shinjan-saha/Canteen-Website/assets/97402824/9dc4993d-33ee-4957-aa15-3ff8c0940852)

The image in the front page can be added hover effect for better user experience.

**Comment by Shinjan-saha** [comment]
Can you explain more briefly?

**Comment by Shinjan-saha** [comment]
Nice, but I don't think this will be essential
