### ISSUE TITLE
Location map should be at center of the web page 

### ISSUE THREAD

**Issue by rko0211** [Shinjan-saha/Canteen-Website#75]
![Screenshot_2024-01-17-10-10-24-693_com android chrome](https://github.com/Shinjan-saha/Canteen-Website/assets/97402824/b33cd90d-6db7-40fd-92d3-9873a504fc9a)

Please review it and assign me this task

**Comment by Shinjan-saha** [comment]
![Screenshot_20240118-185929_Chrome](https://github.com/Shinjan-saha/Canteen-Website/assets/116014977/8516fffd-52b9-4cd8-970b-8233c8499d66)
Ok I will assign that issue buy you also have to make the size of the form big in Mobile version it is small comapre to the location

**Comment by rko0211** [comment]
Ok Assign me this task. Thank you

**Comment by Shinjan-saha** [comment]
Pr Merged

**Comment by rko0211** [comment]
Thank you
