### ISSUE TITLE
feat: Adding a button hover effect in the main page

### ISSUE THREAD

**Issue by Mubashir2611** [Shinjan-saha/Canteen-Website#76]

**Comment by Mubashir2611** [comment]
@Shinjan-saha assign me

**Comment by Shinjan-saha** [comment]
Can you please explain on brief on what images are are exactly going to add hover effect on

**Comment by Mubashir2611** [comment]
![image](https://github.com/Shinjan-saha/Canteen-Website/assets/108177382/127b3134-0f07-4c66-b375-b82d48d1926d)
i want to change this button hover effect when any user hovers this button.

**Comment by Shinjan-saha** [comment]
Issue assigned

**Comment by Shinjan-saha** [comment]
<img width="960" alt="hovereffect" src="https://github.com/Shinjan-saha/Canteen-Website/assets/116014977/b200a61d-a732-433f-8fde-31e6b8d3df73">
Where is the Hover effect on "Order Online " Button????

**Comment by Mubashir2611** [comment]
I think you have to merge my pr first then the feature shows on the website probably. Actually, I test my changes and its work.  You can review my changes if any doubt.

**Comment by Mubashir2611** [comment]
Hey @Shinjan-saha can you please merge my PR kindly.
