### ISSUE TITLE
spell mistake

### ISSUE THREAD

**Issue by arghadipmanna101** [Shinjan-saha/Canteen-Website#77]
Ice-cream spelling mistake in multiple areas...

- Place 1 :
![image](https://github.com/Shinjan-saha/Canteen-Website/assets/130065095/65f9ee93-bfe0-4574-bbb3-ebc5b99b08d1)

- place 2 :
![image](https://github.com/Shinjan-saha/Canteen-Website/assets/130065095/308e21e1-eeb7-48f3-ae2e-182f57240d02)

**Comment by Shinjan-saha** [comment]
Assigned you

**Comment by Shinjan-saha** [comment]
Pr Merged
