### ISSUE TITLE
ADD Smooth Scroll Effect and transition effect in the website 

### ISSUE THREAD

**Issue by rko0211** [Shinjan-saha/Canteen-Website#79]
When user scroll the pages then all items should be translate . For better user experience it is required

**Comment by Shinjan-saha** [comment]
Can you show the demo first?

**Comment by rko0211** [comment]
Visit this website 
https://twogood.com.au/
like that scrolling effect

**Comment by Shinjan-saha** [comment]
Assigned you the issue
