### ISSUE TITLE
adding better hover effects

### ISSUE THREAD

**Issue by YooAshu** [Shinjan-saha/Canteen-Website#83]
![Screenshot (137)](https://github.com/Shinjan-saha/Canteen-Website/assets/95643200/f9c2a87e-cbbe-4ffe-b7f3-adc21703c261)
the cureent hover effect on items does not look good , want to change this, plss assign me for this

**Comment by Shinjan-saha** [comment]
Please show the demo on what changes are you doing

**Comment by YooAshu** [comment]
![Screenshot (139)](https://github.com/Shinjan-saha/Canteen-Website/assets/95643200/c59ee84c-5b14-49ae-8c62-4aab2c9e0a6c)
 @Shinjan-saha

**Comment by Shinjan-saha** [comment]
Nice issue assigned
