### ISSUE TITLE
slider images are not of same height

### ISSUE THREAD

**Issue by YooAshu** [Shinjan-saha/Canteen-Website#84]
![Screenshot (141)](https://github.com/Shinjan-saha/Canteen-Website/assets/95643200/c8774774-8044-42fd-bce1-3221f2ead6f6)
![Screenshot (142)](https://github.com/Shinjan-saha/Canteen-Website/assets/95643200/00c95d0a-e367-4a68-9169-7f9c2c834de4)
the slider images are not of same height , so when slides are chnging positions of each block are changing, which is not a good experience pls assign me this

**Comment by Shinjan-saha** [comment]
Issue assigned
